server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/triple?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf-8
    username: triple
    password: triple
    driver-class-name: com.mysql.cj.jdbc.Driver
    classpath: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    properties:
      hibernate.format_sql: true